### ISSUE TITLE
Plugin causes NetBeans 8.1 to hang when copying text to clipboard.

### ISSUE THREAD

**Issue by nick-dasilva** [markiewb/nb-resource-hyperlink-at-cursor#23] opened 2016-04-12 04:34 UTC
Hi, I've been beating my head against this for a couple of months and finally spent the past several days attempting to narrow down the root cause.

I originally filed the issue on the NetBeans bug tracker before troubleshooting down to this plugin:
https://netbeans.org/bugzilla/show_bug.cgi?id=258709

Preconditions:
1. NetBeans version 8.1 (also works with various nightly development builds from the past three months)
2. Verified under the following OSes:
* Windows 10 ENT x86_64
* Windows 8.1 Pro x86_64
3. Verified under the following JRE versions:
* 1.8.0_55
* 1.8.0_66
* 1.8.0_77

Duplication Steps:
1. Install Open File at Cursor plugin via the NetBeans plugins menu.
2. Restart the IDE.
3. Open any Java source code file.
4. Select multiple lines of text.
5. Rapidly and repeatedly hit Ctrl+C.
6. NetBeans IDE becomes unresponsive to user input, and can only be terminated via Task Manager.

Please see linked NetBeans Bugzilla issue for thread dumps taken during the hang events.

The first two thread dumps were taken while editing a moderately complex Maven EAR project with multiple modules and POM inheritance, as I had initially believed that the issue was related to the IDE's CDI/EJB annotation parser.

The third thread dump was taken while editing a simple Maven Java SE project with only a "main" class file in it.  Looks like line 197 is where that dump gets interesting, and appears to match the profiler output you have screenshotted on issue #3. Possible duplicate?

**Comment by markiewb** [comment] 2016-04-12 19:30
@nick-dasilva: I cannot reproduce it via your steps, but the threaddump at the bugzilla issues contains the same line. So yes, I think it is a duplicate. But don't know yet how to fix. I am not so familiar with the API I am using there.

**Comment by markiewb** [comment] 2016-04-12 19:30
Duplicate of #3

**Closed by markiewb** 2016-04-12 19:30 UTC
Labels: duplicate

**Comment by markiewb** [comment] 2016-04-12 20:23
@nick-dasilva: Please try to reproduce it again using https://github.com/markiewb/nb-resource-hyperlink-at-cursor/releases/download/1.3.2.0/open-file-at-cursor-plugin-1.3.2.0.nbm 

Please give me feedback. If it works for you, then I will publish it officially to the plugin portal
